# Render Blueprint for Whisper Relay Server (Rust)
services:
  - type: web
    name: whisper-relay-rust
    runtime: rust
    plan: free
    buildCommand: cargo build --release
    startCommand: ./target/release/rtce2ee-whisper
    envVars:
      - key: RUST_LOG
        value: info
      - key: PORT
        fromService:
          type: web
          name: whisper-relay-rust
          property: port
    healthCheckPath: /health
